import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#f1f2f6',
  },
  // Drawer flotante
  drawerOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.3)',
    zIndex: 100,
  },
  customDrawerContainer: {
    position: 'absolute',
    top: 65,
    left: 0,
    width: 240,
    height: '100%',
    backgroundColor: '#fff',
    borderTopRightRadius: 30,
    borderBottomRightRadius: 30,
    elevation: 12,
    zIndex: 101,
    paddingTop: 40,
    shadowColor: '#004989',
    shadowOffset: { width: 4, height: 0 },
    shadowOpacity: 0.18,
    shadowRadius: 12,
  },
  drawerItem: {
    borderRadius: 30,
    marginVertical: 2,
    backgroundColor: 'transparent',
  },
  drawerItemActive: {
    borderRadius: 30,
    marginVertical: 2,
    backgroundColor: 'rgba(0,73,137,0.5)', // #004989 con 50% opacidad
  },
  drawerItemLabel: {
    color: '#004989',
    fontWeight: 'bold',
    fontSize: 16,
  },
  drawerItemLabelActive: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
    textShadowColor: 'rgba(0,0,0,0.15)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  // Barra de navegación superior flotante
  appbar: {
    backgroundColor: '#fff',
    elevation: 6,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    zIndex: 10,
  },
  // Logo pequeño para la barra
  logoBar: {
    width: 50,
    height: 50,
  },
  container: {
    flex: 1,
    backgroundColor: 'rgba(255,255,255,0.97)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 30,
    margin: 20,
    borderRadius: 32,
    shadowColor: '#a1a1a1ff',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 8,
  },
  logo: {
    width: 160,
    height: 160,
    marginBottom: 24,
    borderRadius: 80,
    backgroundColor: '#dfe4ea',
  },
  title: {
    fontSize: 26,
    fontWeight: 'bold',
    color: '#2d3436',
    marginBottom: 10,
    letterSpacing: 0.2,
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 16,
    color: '#636e72',
    textAlign: 'center',
    marginTop: 8,
    marginBottom: 24,
    letterSpacing: 0.5,
  },
  button: {
    backgroundColor: '#004989',
    borderRadius: 30,
    paddingVertical: 12,
    paddingHorizontal: 36,
    marginTop: 10,
    shadowColor: '#004989',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.18,
    shadowRadius: 8,
    elevation: 4,
  },
  buttonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
    letterSpacing: 1, // <-- Completa el valor aquí
  },
});